#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p snapcraft 
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p snapcraft /usr/share/snapcraft
fi

# End automatically added section
